/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.hilgardvr.swingy.view;

import com.gmail.hilgardvr.swingy.model.characters.*;
import com.gmail.hilgardvr.swingy.model.Directions;
/**
 *
 * @author hilgard
 */
public class GameGui extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public GameGui(Hero hero) {
        initComponents();
        MoveBox.removeAllItems();
        for (Directions d : Directions.values()) {
            MoveBox.addItem(d.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LocationLabel = new javax.swing.JLabel();
        LocationField = new javax.swing.JTextField();
        HeroStatsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HeroStatsField = new javax.swing.JTextArea();
        OutputLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FightResultsFields = new javax.swing.JTextArea();
        EnemyStatsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        EnemyStatsField = new javax.swing.JTextArea();
        MoveLabel = new javax.swing.JLabel();
        MoveBox = new javax.swing.JComboBox<>();
        FightButton = new javax.swing.JButton();
        RunButton = new javax.swing.JButton();
        MapSizeLabel = new javax.swing.JLabel();
        MapSizeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LocationLabel.setText("Your Location:");

        HeroStatsLabel.setText("Your Stats: ");

        HeroStatsField.setColumns(20);
        HeroStatsField.setRows(5);
        jScrollPane1.setViewportView(HeroStatsField);

        OutputLabel.setText("Output:");

        FightResultsFields.setColumns(20);
        FightResultsFields.setRows(5);
        jScrollPane2.setViewportView(FightResultsFields);

        EnemyStatsLabel.setText("Enemy Stats:");

        EnemyStatsField.setColumns(20);
        EnemyStatsField.setRows(5);
        jScrollPane3.setViewportView(EnemyStatsField);

        MoveLabel.setText("Move:");

        MoveBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FightButton.setText("Fight");

        RunButton.setText("Run");

        MapSizeLabel.setText("Map Size:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocationLabel)
                            .addComponent(MoveLabel)
                            .addComponent(MapSizeLabel)
                            .addComponent(OutputLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(HeroStatsLabel)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MoveBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MapSizeField))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnemyStatsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnemyStatsLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LocationLabel)
                            .addComponent(LocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HeroStatsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MapSizeLabel)
                            .addComponent(MapSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MoveLabel)
                            .addComponent(MoveBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutputLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FightButton)
                    .addComponent(RunButton))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addMoveListener(java.awt.event.ActionListener a) {
        MoveBox.addActionListener(a);
    }
    
    public void addFightListener(java.awt.event.ActionListener a) {
        FightButton.addActionListener(a);
    }
    
    public void addRunListener(java.awt.event.ActionListener a) {
        RunButton.addActionListener(a);
    }

    public void setLocationField(String str) {
        LocationField.setText("");
        LocationField.setText(str);
    }

    public void setHeroStatsField(String str) {
        HeroStatsField.setText("");
        HeroStatsField.setText(str);
    }

    public String getDirectionBox() {
        if (MoveBox.getSelectedItem() != null) {
            return MoveBox.getSelectedItem().toString();
        }
        return null;
    }

    public void setEnemyStatsField(String str) {
        EnemyStatsField.setText("");
        EnemyStatsField.setText(str);
    }

    public void enableButtons() {
        FightButton.setEnabled(true);
        RunButton.setEnabled(true);
    }

    public void disableButtons() {
        FightButton.setEnabled(false);
        RunButton.setEnabled(false);
    }

    public void enableBox() {
        MoveBox.setEnabled(true);
    }

    public void disableBox() {
        MoveBox.setEnabled(false);
    }

    public void setFightResultsFields(String str) {
        FightResultsFields.setText(str);
    }

    public String getFightResultsField() {
        return FightResultsFields.getText();
    }
    
    public void setMapSizeField(String str) {
        MapSizeField.setText(str);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EnemyStatsField;
    private javax.swing.JLabel EnemyStatsLabel;
    private javax.swing.JButton FightButton;
    private javax.swing.JTextArea FightResultsFields;
    private javax.swing.JTextArea HeroStatsField;
    private javax.swing.JLabel HeroStatsLabel;
    private javax.swing.JTextField LocationField;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JTextField MapSizeField;
    private javax.swing.JLabel MapSizeLabel;
    private javax.swing.JComboBox<String> MoveBox;
    private javax.swing.JLabel MoveLabel;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JButton RunButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
