/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.hilgardvr.swingy.view;

import com.gmail.hilgardvr.swingy.controller.GuiGameLauncher;

/**
 *
 * @author hilgard
 */
public class LaunchGui extends javax.swing.JFrame {

    /**
     * Creates new form LaunchGui
     */
    public LaunchGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateNewLabel = new javax.swing.JLabel();
        LoadSavedLabel = new javax.swing.JLabel();
        CreateNew = new javax.swing.JButton();
        LoadSaved = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateNewLabel.setText("Create New Hero");

        LoadSavedLabel.setText("Load Saved Hero");

        CreateNew.setText("Create");
        /*CreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewActionPerformed(evt);
            }
        });*/

        LoadSaved.setText("Load");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoadSavedLabel)
                    .addComponent(CreateNewLabel))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadSaved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewLabel)
                    .addComponent(CreateNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadSavedLabel)
                    .addComponent(LoadSaved))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*private void CreateNewActionPerformed(java.awt.event.ActionEvent evt) {
    }*/

    public void addNewHeroListener(java.awt.event.ActionListener a) {
        CreateNew.addActionListener(a);
    }
    
    public void addLoadHeroListener(java.awt.event.ActionListener a) {
        LoadSaved.addActionListener(a);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNew;
    private javax.swing.JLabel CreateNewLabel;
    private javax.swing.JButton LoadSaved;
    private javax.swing.JLabel LoadSavedLabel;
    // End of variables declaration//GEN-END:variables
}
