/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.hilgardvr.swingy.view;

import com.gmail.hilgardvr.swingy.model.characters.Hero;
import java.util.ArrayList;

/**
 *
 * @author hilgard
 */
public class LoadHero extends javax.swing.JFrame {
    ArrayList<Hero> heroList;
    /**
     * Creates new form LoadHero
     */
    public LoadHero(ArrayList<Hero> heroList) { //
        initComponents();
        this.heroList = heroList;
        HeroNameBox.removeAllItems();
        HeroAttField.setText("");
        for (Hero hero : heroList) {
            HeroNameBox.addItem(hero.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeroNameLabel = new javax.swing.JLabel();
        HeroAttLabel = new javax.swing.JLabel();
        HeroNameBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        HeroAttField = new javax.swing.JTextArea();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeroNameLabel.setText("Availible Heroes");

        HeroAttLabel.setText("Hero Attributes");

        HeroNameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        HeroNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeroNameBoxActionPerformed(evt);
            }
        });

        HeroAttField.setColumns(20);
        HeroAttField.setRows(5);
        jScrollPane1.setViewportView(HeroAttField);

        SubmitButton.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HeroNameLabel)
                            .addComponent(HeroNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(SubmitButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeroAttLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeroNameLabel)
                    .addComponent(HeroAttLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HeroNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(SubmitButton)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Hero getBoxHero() {
        Hero returnHero = null;
        if (HeroNameBox.getSelectedItem() != null) {
            String heroName = HeroNameBox.getSelectedItem().toString();
            for (Hero hero : heroList) {
                if (hero.getName().equals(heroName)) {
                    returnHero = hero;
                    break;
                }
            }
        }
        return returnHero;
    }
    
    private void HeroNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeroNameBoxActionPerformed
        Hero hero = getBoxHero();
        if (hero != null) {
            HeroAttField.setText("");
            HeroAttField.append(getBoxHero().toString());
        }
    }//GEN-LAST:event_HeroNameBoxActionPerformed

    public void addSubmitListener(java.awt.event.ActionListener a) {
        SubmitButton.addActionListener(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea HeroAttField;
    private javax.swing.JLabel HeroAttLabel;
    private javax.swing.JComboBox<String> HeroNameBox;
    private javax.swing.JLabel HeroNameLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
